FROM sideex/webservice-base

USER sideex

COPY sideex-webservice.sh /opt/sideex-webservice/
COPY serviceconfig.json /opt/sideex-webservice/
COPY serviceconfig.json /opt/sideex-webservice/
COPY sideex-service.conf /etc/supervisor/conf.d/

EXPOSE 50000
